name: Open Documentation Issue

on:
  push:
    branches:
      - master

jobs:
  open-issue:
    runs-on: ubuntu-latest
    steps:
      - name: Open an Issue in Documentation Repo
        uses: peter-evans/create-issue-from-file@v3
        env:
          GITHUB_TOKEN: ${{ secrets.DOCUMENTATIONTOKEN }}
        with:
          title: "Documentation Update Needed"
          content-filepath: /path/to/a/file/containing/issue/body.md  # optional, you can also directly write the content here
          labels: documentation, update
          repository: kbennett2000/hello-world-docs
