name: Open Documentation Issue

on:
  push:
    branches:
      - master

jobs:
  open_issue:
    runs-on: ubuntu-latest

    steps:
      - name: Open documentation issue
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.DOCUMENTATIONTOKEN }}
          script: |
            github.rest.issues.create({
              owner: context.repo.owner,
              repo: 'hello-world-docs',
              title: 'Update documentation for changes in ${{ github.repository }}',
              body: 'Changes have been made in the ${{ github.repository }} repository.\nPlease review and update the documentation accordingly.\nCommit: ${{ github.sha }}\nRepository: ${{ github.repository }}'
            })
