name: Open Documentation Issue

on:
  push:
    branches:
      - main

jobs:
  open_issue:
    runs-on: ubuntu-latest

    steps:
      - name: Open documentation issue
        uses: octokit/request-action@v2.x
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          route: POST /repos/${{ github.repository }}/issues
          mediaType: application/json
          title: Update documentation for changes in ${{ github.repository }}
          body: |
            Changes have been made in the ${{ github.repository }} repository.
            Please review and update the documentation accordingly.

            Commit: ${{ github.sha }}
            Repository: ${{ github.repository }}
