name: Open Documentation Issue

on:
  push:
    branches:
      - master

jobs:
  open_issue:
    runs-on: ubuntu-latest

    steps:
      - name: Open documentation issue
        uses: octokit/request-action@v2.x
        env:
          GITHUB_TOKEN: ${{ secrets.DOCUMENTATIONTOKEN }}
        with:
          route: POST /repos/${{ github.repository_owner }}/hello-world-docs/issues
          mediaType: |
            {
              "title": "Update documentation for changes in ${{ github.repository }}",
              "body": "Changes have been made in the ${{ github.repository }} repository.\nPlease review and update the documentation accordingly.\nCommit: ${{ github.sha }}\nRepository: ${{ github.repository }}"
            }
