name: Open Documentation Issue

on:
  push:
    branches:
      - master

jobs:
  open_issue:
    runs-on: ubuntu-latest

    steps:
      - name: Open documentation issue
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.DOCUMENTATIONTOKEN }}
          script: |
            const compareUrl = `https://github.com/${{ github.repository }}/compare/${{ github.event.before }}...${{ github.sha }}`;
            const issueBody = `Changes have been made in the ${{ github.repository }} repository. Please review and update the documentation accordingly.
            
            Commit: ${{ github.sha }}
            Repository: ${{ github.repository }}
            Changes: ${compareUrl}`;

            github.rest.issues.create({
              owner: context.repo.owner,
              repo: 'hello-world-docs',
              title: 'Update documentation for changes in ${{ github.repository }}',
              body: issueBody
            });
